AllCops:
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'config/**/*'
    - 'script/**/*'
  TargetRubyVersion: 2.5

Rails:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Metrics/LineLength:
  Max: 120

Style/BlockDelimiters:
  Exclude:
    - spec/**/*_spec.rb

Style/BracesAroundHashParameters:
  Exclude:
    - spec/**/*_spec.rb

Layout/EmptyLinesAroundClassBody:
  EnforcedStyle: empty_lines

Layout/SpaceAroundBlockParameters:
  EnforcedStyleInsidePipes: no_space

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
      default: []
      '%i': '[]'
      '%I': '[]'
      '%r': '{}'
      '%w': '[]'
      '%W': '[]'